<a href="https://colab.research.google.com/github/jessicabassim82-del/online-retail-etl-analysis/blob/main/Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import sqlite3
from google.colab import files

In [3]:
df = pd.read_csv("/content/online_retail_II.csv", on_bad_lines='skip', encoding='ISO-8859-1')
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [5]:
df.dropna(inplace=True)


if 'InvoiceDate' in df.columns:
    df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'], errors='coerce')


if 'Quantity' in df.columns and 'Price' in df.columns:
    df['Total'] = df['Quantity'] * df['Price']


conn = sqlite3.connect('online_retail.db')
df.to_sql('sales', conn, if_exists='replace', index=False)




query_top_products = """
SELECT Description, SUM(Total) as TotalSales
FROM sales
GROUP BY Description
ORDER BY TotalSales DESC
LIMIT 10;
"""


query_monthly_revenue = """
SELECT strftime('%Y-%m', InvoiceDate) as Month, SUM(Total) as Revenue
FROM sales
GROUP BY Month
ORDER BY Month;
"""


top_products = pd.read_sql(query_top_products, conn)
monthly_revenue = pd.read_sql(query_monthly_revenue, conn)

print("Top 10 Products by Sales:")
display(top_products)

print("Monthly Revenue Trends:")
display(monthly_revenue)

Top 10 Products by Sales:

                           Description  TotalSales
0      PAPER CHAIN KIT 50'S CHRISTMAS      4530.90
1   WHITE HANGING HEART T-LIGHT HOLDER     4042.20
2  ROTATING SILVER ANGELS T-LIGHT HLDR     3880.35
3              EDWARDIAN PARASOL BLACK     3599.65
4        ASSORTED COLOUR BIRD ORNAMENT     2925.77
5                EDWARDIAN PARASOL RED     2798.25
6      RED/WHITE DOTS RUFFLED UMBRELLA     2340.85
7            EDWARDIAN PARASOL NATURAL     2151.05
8     BLACK/BLUE DOTS RUFFLED UMBRELLA     2007.65
9                  WHITE CHERRY LIGHTS     1907.70

Monthly Revenue Trends:

     Month    Revenue
0  2009-12  186161.44